### PR TITLE
Added crashlytics(fabric)

### PR DESCRIPTION
**Pull request by ankittale**
Hey please add this app is working fine !!

### CODE REVIEW

**Comment by ankittale** [comment]
Any issue regarding fabric. Please let me know. I know the way to hide key from PC but I think it would better if you keep the key as main main author

**Comment by ankittale** [comment]
on our project, we also had fabric key in manifest because of it just a crashlytics. And after update please update status for me to "UPDATE" fork from my side.

**Comment by tal32123** [comment]
Hi Ankit,

I added your code and hid the key all that needs to be done is copy/paste
into manifest for it to work.

Can you please send me your email? I'll add you to slack channel.

Thanks,
Tal

**Comment by ankittale** [comment]
Yeah sure I my email is ankittale@hotmail.com

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Pull request merged**
